version: '3.8'

services:
  apache:
    image: httpd:latest
    container_name: meu_servidor_apache
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./html:/usr/local/apache2/htdocs