version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: meu_banco_mongo
    restart: always
    ports: 
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: caio
      MONGO_INITDB_ROOT_PASSWORD: caio
      MONGO_INITDB_DATABASE: banana
    volumes:
      - ./data:/data/db
      - ./conf/mongod.conf:/etc/mongo/mongod.conf
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017 --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: caio
      ME_CONFIG_MONGODB_ADMINPASSWORD: caio
      ME_CONFIG_MONGODB_URL: mongodb://caio:caio@mongodb:27017/
    depends_on:
      mongodb:
        condition: service_healthy